
[package]
name = "redis_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.140"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }





